services:
  app:
    image: ghcr.io/medvesek/laravel-example:latest
    configs:
      - source: laravel_example_env
        target: /var/www/html/.env
    networks:
      - default
      - traefik-net
    deploy:
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 15s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.laravel_example.rule=Host(`laravel-example.ajmuht.eu`)"
        - "traefik.http.routers.laravel_example.tls.certresolver=le"
        - "traefik.http.services.laravel_example.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true

configs:
  laravel_example_env:
    external: true
