services:
  app:
    image: ghcr.io/medvesek/laravel-example:latest
    depends_on:
      postgres:
        condition: service_started
    env_file: .env
    networks:
      - default
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel_example.rule=Host(`laravel-example.ajmuht.eu`)"
      - "traefik.http.routers.laravel_example.entrypoints=websecure"
      - "traefik.http.routers.laravel_example.tls.certresolver=le"
      - "traefik.http.services.webapp.loadbalancer.server.port=80"
    expose:
      - 80
      - 443

  postgres:
    image: postgres:17
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}

volumes:
  postgresdata:

networks:
  traefik-net:
    external: true
