services:
    app:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
            target: dev
        user: 1000:1000
        ports:
            - 80:80
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html/

    postgres:
        image: postgres:17
        volumes:
            - postgresdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: root
            POSTGRES_DB: laravel

volumes:
    postgresdata:
