services:
    nginx:
        image: nginx:latest
        depends_on:
            php:
                condition: service_started
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
        ports:
            - 80:80
    php:
        build:
            context: ./docker/php
            target: base
        user: 1000:1000
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html/

    postgres:
        image: postgres:17
        volumes:
            - postgresdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: root
            POSTGRES_DB: laravel

volumes:
    postgresdata:
