services:
  postgres:
    image: postgres:17
    networks:
      - laravel-example-net
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}

volumes:
  postgresdata:

networks:
  laravel-example-net:
    external: true
