- name: Deploy
  hosts: all
  tasks:
    - name: Deploy
      include_role:
        name: medvesek.deploy.deploy
      vars:
        app_name: laravel-example
        source: ./dist
        pre-deploy:
          - name: Migrate db
            image: ghcr.io/medvesek/laravel-example:latest
            command: php artisan migrate --force
