- name: Deploy
  hosts: all
  tasks:
    - name: python3-dotenv-cli
      package:
        name: python3-dotenv-cli
        state: present

    - name: Create config foo
      community.docker.docker_config:
        name: laravel_example_env
        data: |
          {{ lookup("env", "ENV_PROD") }}
        state: present

    - name: Copy docker compose app
      ansible.builtin.copy:
        src: ./docker-compose-app-prod.yml
        dest: ~/docker/apps/laravel-example/docker-compose-app.yml

    - name: Copy docker compose db
      ansible.builtin.copy:
        src: ./docker-compose-db-prod.yml
        dest: ~/docker/apps/laravel-example/docker-compose-db.yml

    - name: Env
      ansible.builtin.copy:
        content: |
          {{ lookup("env", "ENV_PROD") }}
        dest: ~/docker/apps/laravel-example/.env

    - name: Create a network
      community.docker.docker_network:
        name: laravel-example-net
        driver: overlay

    - name: Deploy db
      shell: dotenv docker stack deploy -c docker-compose-db.yml laravel-example-db
      args:
        chdir: /root/docker/apps/laravel-example

    - name: Migrate
      command: |
        docker service create
        --name migration
        --mode replicated-job
        --restart-condition none
        --env-file .env
        --network laravel-example-net
        ghcr.io/medvesek/laravel-example:latest
        php artisan migrate --force
      args:
        chdir: /root/docker/apps/laravel-example

    - name: Remove migration service
      command: |
        docker service rm migration

    - name: Deploy app
      community.docker.docker_stack:
        state: present
        name: laravel-example-app
        compose:
          - /root/docker/apps/laravel-example/docker-compose-app.yml

    - name: Optimize
      command: docker compose run --rm app php artisan optimize
      args:
        chdir: ~/docker/apps/laravel-example
