- name: Deploy
  hosts: all
  tasks:
    - name: pip
      package:
        name: python3-pip
        state: present

    - name: python-dotenv
      pip:
        name: python-dotenv
        state: present

    - name: Copy docker compose app
      ansible.builtin.copy:
        src: ./docker-compose-app-prod.yml
        dest: ~/docker/apps/laravel-example/docker-compose-app.yml

    - name: Copy docker compose db
      ansible.builtin.copy:
        src: ./docker-compose-db-prod.yml
        dest: ~/docker/apps/laravel-example/docker-compose-db.yml

    - name: Env
      ansible.builtin.copy:
        content: |
          {{ lookup("env", "ENV_PROD") }}
        dest: ~/docker/apps/laravel-example/.env

    - name: Create a network
      community.docker.docker_network:
        name: laravel-example-net
        driver: overlay

    - name: Deploy db
      shell: dotenv run -- docker stack deploy -c - laravel-example-db
      args:
        chdir: /root/docker/apps/laravel-example

    - name: Migrate
      command: docker service create --name migration --detach=false --restart-condition none --config source=laravel_example_env,target=/var/www/html/.env --network laravel-example-net ghcr.io/medvesek/laravel-example:latest php artisan migrate

    - name: Deploy app
      community.docker.docker_stack:
        state: present
        name: laravel-example-app
        compose:
          - /root/docker/apps/laravel-example/docker-compose-app.yml

    - name: Optimize
      command: docker compose run --rm app php artisan optimize
      args:
        chdir: ~/docker/apps/laravel-example
