- name: Deploy
  hosts: all
  tasks:
    - name: Deploy
      include_role:
        name: medvesek.deploy.deploy
      vars:
        app_name: laravel-example
        source: ./dist
        expose:
          - service: app
            entrypoints: websecure
            port: 80
        pre_deploy:
          - name: laravel_example_migrate_db
            image: ghcr.io/medvesek/laravel-example:latest
            command: php artisan migrate --force
