name: Workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: composer:2.2.25
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Composer
        run: composer install
