name: Workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: composer:2.2.25
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Composer
        run: composer install

  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          file: "{context}/docker/php/Dockerfile"
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
